# Generated by Django 4.1.7 on 2023-03-13 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0004_add_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 14, 1, 58, 288649, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 14, 1, 58, 288702, tzinfo=datetime.timezone.utc)),
        ),
    ]
